name: MCdatabase
version: 1.0
main: agjoku.mcdatabase.MCdatabase
api-version: '1.20'

commands:
  hashing:
    description: hashing command
    usage: /hashing <HashAlgorithm> <String> <copy clipboard>

  agdb:
    description: access ag db
    usage: /agdb <username> <password>
